import type { WorkflowStep } from '../types';

export interface WorkflowValidationResult {
  ok: boolean;
  errors: string[];
}

/**
 * Validate a workflow graph generated by the agent. Checks:
 *   - non-empty
 *   - unique ids
 *   - every `next` points to an existing step
 *   - every branch target points to an existing step
 *   - at least one `end` step
 *   - starting from the first step, an `end` is reachable
 */
export function validateWorkflow(workflow: WorkflowStep[]): WorkflowValidationResult {
  const errors: string[] = [];

  if (workflow.length === 0) {
    return { ok: false, errors: ['workflow is empty'] };
  }

  const ids = new Set<string>();
  const duplicates = new Set<string>();
  for (const step of workflow) {
    if (ids.has(step.id)) duplicates.add(step.id);
    ids.add(step.id);
  }
  for (const dup of duplicates) {
    errors.push(`duplicate step id: ${dup}`);
  }

  const byId = new Map(workflow.map((s) => [s.id, s]));
  const hasEnd = workflow.some((s) => s.kind === 'end');
  if (!hasEnd) {
    errors.push('workflow must contain at least one end step');
  }

  for (const step of workflow) {
    if (step.kind === 'end') continue;
    if (step.kind === 'branch') {
      if (step.branches.length === 0) {
        errors.push(`branch ${step.id} has no branches`);
      }
      for (const br of step.branches) {
        if (!byId.has(br.next)) {
          errors.push(`branch ${step.id} references missing step id: ${br.next}`);
        }
      }
      continue;
    }
    if ('next' in step && step.next) {
      if (!byId.has(step.next)) {
        errors.push(`step ${step.id} references missing next step id: ${step.next}`);
      }
    }
  }

  if (errors.length === 0 && !canReachEnd(workflow, byId)) {
    errors.push('unreachable: no path from first step to any end');
  }

  return { ok: errors.length === 0, errors };
}

function canReachEnd(
  workflow: WorkflowStep[],
  byId: Map<string, WorkflowStep>
): boolean {
  const start = workflow[0];
  if (!start) return false;
  const stack: WorkflowStep[] = [start];
  const seen = new Set<string>();
  while (stack.length > 0) {
    const step = stack.pop()!;
    if (seen.has(step.id)) continue;
    seen.add(step.id);
    if (step.kind === 'end') return true;
    if (step.kind === 'branch') {
      for (const br of step.branches) {
        const next = byId.get(br.next);
        if (next) stack.push(next);
      }
      continue;
    }
    if ('next' in step && step.next) {
      const next = byId.get(step.next);
      if (next) stack.push(next);
    }
  }
  return false;
}
